# Service definitions for Energy Dispatcher
# Translations are provided in translations/en.json and translations/sv.json
# The services.yaml file provides the schema and UI selectors

battery_cost_reset:

battery_cost_set_soc:
  fields:
    soc_percent:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box

create_dashboard_notification:

schedule_appliance:
  fields:
    appliance:
      required: true
      selector:
        select:
          options:
            - "dishwasher"
            - "washing_machine"
            - "water_heater"
    power_w:
      required: true
      selector:
        number:
          min: 100
          max: 10000
          step: 50
          unit_of_measurement: "W"
    duration_hours:
      required: true
      selector:
        number:
          min: 0.25
          max: 12
          step: 0.25
          unit_of_measurement: "hours"
    earliest_start:
      required: false
      selector:
        time:
    latest_end:
      required: false
      selector:
        time:

set_export_mode:
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - "never"
            - "excess_solar_only"
            - "peak_price_opportunistic"
    min_export_price:
      required: false
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "SEK/kWh"

override_battery_mode:
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - "charge"
            - "discharge"
            - "hold"
            - "auto"
    duration_minutes:
      required: false
      default: 60
      selector:
        number:
          min: 5
          max: 1440
          step: 5
          unit_of_measurement: "min"
    power_w:
      required: false
      selector:
        number:
          min: 500
          max: 20000
          step: 100
          unit_of_measurement: "W"
