energy_dispatcher.set_manual_ev:
  name: Set Manual EV SOC and Target
  fields:
    soc_current:
      example: 45
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    soc_target:
      example: 80
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

energy_dispatcher.ev_force_charge:
  name: EV Force Charge
  fields:
    duration:
      example: 60
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: min
    current:
      example: 16
      selector:
        number:
          min: 6
          max: 16
          unit_of_measurement: A

energy_dispatcher.ev_pause:
  name: EV Pause
  fields:
    duration:
      example: 30
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: min

energy_dispatcher.force_battery_charge:
  name: Battery Force Charge
  fields:
    power_w:
      example: 10000
      selector:
        number:
          min: 1000
          max: 20000
          unit_of_measurement: W
    duration:
      example: 90
      selector:
        number:
          min: 5
          max: 240
          unit_of_measurement: min
