set_manual_ev:
  name: Set manual EV SOC
  description: Uppdatera manuell EV SOC
  fields:
    soc_current:
      name: Current SOC
      description: Nuvarande EV-batteri %
      example: 40
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box
    soc_target:
      name: Target SOC
      description: Mål-SoC för EV %
      example: 80
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box

ev_force_charge:
  name: EV force charge
  description: Starta EV-laddning en tid med visst strömvärde
  fields:
    duration:
      name: Duration (minuter)
      example: 60
      required: false
      selector:
        number:
          min: 1
          max: 480
          unit_of_measurement: "min"
    current:
      name: Laddström (A)
      example: 16
      required: false
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"

ev_pause:
  name: EV pause
  description: Pausa EV-laddning i angivet antal minuter
  fields:
    duration:
      name: Duration (minuter)
      example: 30
      required: false
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: "min"

force_battery_charge:
  name: Force battery charge
  description: Ladda batteriet med angiven effekt om adapter stödjer det
  fields:
    power_w:
      name: Effekt (W)
      example: 10000
      required: false
      selector:
        number:
          min: 500
          max: 20000
          unit_of_measurement: "W"
    duration:
      name: Duration (minuter)
      example: 60
      required: false
      selector:
        number:
          min: 1
          max: 480
          unit_of_measurement: "min"
