name: Sample data report

on:
  workflow_dispatch:
  push:
    paths:
      - "tests/fixtures/**"
      - "tests/data_quality_report.py"

permissions:
  contents: write

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate report
        run: |
          python tests/data_quality_report.py
          test -f docs/generated/sample_data_report.md

      - name: Commit report if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add docs/generated/sample_data_report.md
            git commit -m "chore: update sample data report"
            git push
          else
            echo "No changes to commit."
          fi
